name: Test before push
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          yarn install
          yarn jest